#!/usr/bin/env bash

set -e

# Fetches a GitHub PR as a local branch
#
#   $ git fetch-pr <PR-number> <branch-name>
#
# e.g. 
#   $ git fertch-pr 97 my-fancy-branch
#
# More: https://help.github.com/articles/checking-out-pull-requests-locally/

if [ $# -eq 2 ]; then
  git fetch origin pull/${1}/head:${2}
else
  echo "Usage: git fetch-pr <pr-number> <branch-name>"
fi