#!/usr/bin/env bash

# When done resolving conflicts while cherry-picking, call `g acpc` to confirm your commit message
# and continue.

if [ $# -gt 0 ]; then
	args="$@"
else
	args=.
fi

git add "$args" && git cherry-pick --continue
