#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  git status -s
else
  grep_args=()
  if [ "$1" == -i ]; then
    grep_args=(-i)
    shift
  fi
  arg="$1"; shift
  git status -s "$@" | grep "${grep_args[@]}" "^$arg " | cut -c4-
fi
