#!/bin/sh

cwd="$(pwd)"
. git-cd-to-root
root="$(pwd)"

if [ "${cwd:${#cwd}-1}" != '/' ]; then
   cwd="$cwd/"
fi

if [ "${root:${#root}-1}" != '/' ]; then
   root="$root/"
fi

if [ "${cwd:0:${#root}}" != "$root" ]; then
    echo "Error: git root $root not an ancestor of current directory $cwd."
    exit 1
fi

remnant="${cwd:${#root}}"
if [ -z "$remnant" ]; then
    remnant="./"
fi
echo "$remnant"
