#!/bin/bash

git branch -rvv | \
awk -F' ' '{print $1}' | \
xargs git --no-pager show -s --format="%d %h %ci (%cr) %s" | \
sed -n "s/\(.\)/\1/p" | \
"$(dirname "${BASH_SOURCE[0]}")"/../util/remote_branch_infos.py

