#!/usr/bin/env python
import sys
import webbrowser

if __name__ == '__main__':
    sys.path.append('.')
from util import github


PAGES = ['', 'issues', 'pulls', 'commits', 'wiki', 'pulse', 'graphs']


def usage():
    sys.stderr.write('''Usage: %s [page]

Where page is one of {%s}. If page is not specified, opens the repo root.
''' % (sys.argv[0], ', '.join(PAGES[1:])))
    sys.exit(1)


if __name__ == '__main__':
    if len(sys.argv) > 2:
        usage()

    page = sys.argv[1] if len(sys.argv) > 1 else ''
    if page not in PAGES:
        usage()

    remotes = github.get_github_remotes()
    if len(remotes) == 0:
        sys.stderr.write("There are no github remotes for this repo, "
                         "or perhaps you're not in a git repo.\n")
        sys.exit(1)

    remote = remotes[0].group('path')
    if len(remotes) > 1:
        chosen_remote = remotes[0].groupdict()['path']
        sys.stderr.write('Found multiple remotes. Using %s\n' % chosen_remote)

    webbrowser.open_new_tab(github.make_github_url(remote) + '/' + page)
    sys.exit(0)
