#!/usr/bin/env python
import sys
import webbrowser

from util.remotes import get_remotes


def make_issues_url(remote):
    '''Takes the bit of a remote after github.com and returns an issues URL.'''
    # remote looks like 'foo/bar.git'
    assert '.git' in remote
    return 'https://github.com/%s/issues' % remote.replace('.git', '')


def open_issues_url(remote):
    webbrowser.open_new_tab(make_issues_url(remote))
    sys.exit(0)


for remote in get_remotes().values():
    print remote.group()
    if remote.group('host') == 'github.com':
        open_issues_url(remote.group('path'))

sys.stderr.write('Unable to find a github.com remote!\n')
sys.exit(1)
