#!/usr/bin/env python
import re
import subprocess
import sys
import webbrowser


def make_issues_url(remote):
    '''Takes the bit of a remote after github.com and returns an issues URL.'''
    # remote looks like 'foo/bar.git'
    assert '.git' in remote
    return 'https://github.com/%s/issues' % remote.replace('.git', '')


def open_issues_url(remote):
    webbrowser.open_new_tab(make_issues_url(remote))
    sys.exit(0)


output = subprocess.check_output(['git', 'remote', '-v'])
remotes = output.split('\n')
for remote in remotes:
    m = re.search(r'\thttps?://github.com/([^ ]+) \(push\)$', remote)
    if m: open_issues_url(m.group(1))

    # Try an SSH remote
    m = re.search(r'@github.com:([^ ]+) \(push\)$', remote)
    if m: open_issues_url(m.group(1))


sys.stderr.write('Unable to find a github.com remote!\n')
sys.exit(1)
