#!/usr/bin/env bash
#
# Print the hash of a blob (at a given commit, or staged in the index)
#
# Usage:
#
# $ git blob-sha [-i] [-s] [<tree>:]<path>
#
# "-i" is exclusive with [<tree>:]

set -e

index=
short_sha=
OPTIND=1
while getopts "is" opt; do
  case "$opt" in
    i) index=1 ;;
    s) short_sha=1 ;;
    *) ;;
  esac
done
shift $((OPTIND-1))

usage() {
  echo "Usage: $0 [-i] [-s] [<tree>:<path> | <tree> <path>]" >&2
  exit 1
}

no_index() {
  if [ -n "$index" ]; then
    echo "Can't specify both -i (index) and a <tree>" >&2
    usage
  fi
}

if [ $# -eq 1 ]; then
  spec="$1"; shift
  sha="${spec%%:*}"
  if [ "$sha" == "$spec" ]; then
    sha=HEAD
  else
    no_index
  fi
  path="${spec#*:}"
elif [ $# -eq 2 ]; then
  no_index
  sha="$1"; shift
  path="$1"; shift
else
  usage
fi

flags=()
if [ -n "$short_sha" ]; then
  flags+=( "--abbrev" )
fi

if [ -n "$index" ]; then
  git ls-files --stage "${flags[@]}" -- "$path" | awk '{ print $2 }'
else
  git ls-tree "${flags[@]}" "$sha" -- "$path" | awk '{ print $3 }'
fi
