#!/usr/bin/env bash
#
# Rewrite committer/author info from a given email to a new name/email
#
# Based on https://docs.github.com/en/github/using-git/changing-author-info
#
# Usage:
#
# $ git rewrite-author <old email> <correct name> <correct email>

if [ $# -eq 1 ]; then
  export OLD_EMAIL="$1"; shift
  export CORRECT_NAME="$(git config user.name)"; shift
  export CORRECT_EMAIL="$(git config user.email)"; shift
elif [ $# -eq 3 ]; then
  export OLD_EMAIL="$1"; shift
  export CORRECT_NAME="$1"; shift
  export CORRECT_EMAIL="$1"; shift
else
  echo "Usage: $0 <old email> <correct name> <correct email>" >&2
  exit 1
fi

git filter-branch --env-filter '
if [ -z "$OLD_EMAIL" ]; then exit; fi
if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]; then
  export GIT_COMMITTER_NAME="$CORRECT_NAME"
  export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]; then
  export GIT_AUTHOR_NAME="$CORRECT_NAME"
  export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
