#!/usr/bin/env bash

# Display history of files, lookup by partial/grep matches, prompt to disambiguate if multiple.

pattern="$1"
shift
files=$(git ls-files | grep --color=never "$pattern")
if [ $(count $files) -eq 1 ]; then
    git log -p --follow "$@" -- $files
else
    select filename in $files; do
        echo $filename
        set -v
        git log -p --follow "$@" -- "$filename"
        set +v
        break
    done
fi
