#!/usr/bin/env bash

set -e
source "$GIT_HELPERS_HOME"/test/.helpers-rc

check_cmd() {
  # Verify that a command yields the same output in tmp1 and in its mirror/clone tmp2.
  "$@" > /dev/null
  diff <("$@") <(cd "$tmp2" && "$@")
}

# Create a dummy git repository with one file and one commit, that we will manipulate and from
# `copy-diffs` from in various ways.
cd "$tmp1"
git init
echo foo > asdf
git add asdf
git commit -m "first commit"
[ "$(git current-branch)" == "master" ]


# Initialize a temporary "to" repo to mirror to; perform an initial sync.
git add-mirror-remote tmp2 "$tmp2"
git copy-diffs tmp2

check_hashes() {
  git ls-files | xargs shasum
}

check_cmd check_hashes

# After an initial copy-diffs, various vital stats should be identical across the two repos.
check_cmd git status -s
check_cmd git current-branch
check_cmd git local-branches
check_cmd git for-each-ref

# Create a local branch `test`, verify that we have two local branches, `master` and `test`, and
# that tmp2 doesn't have `test` yet.
git checkout -b test
[ "$(git current-branch)" == "test" ]

cat >expected <<EOF
master
test
EOF
diff <(git local-branches) expected
rm -f expected

# `git local-branches` returns different things between the two repos, because `test` branch hasn't
# been copied yet.
! check_cmd git local-branches

git copy-diffs tmp2
check_cmd git status -s
check_cmd git current-branch
check_cmd git local-branches
check_cmd git for-each-ref

# Switch back to `master` branch, verify that copy-diffs pushs that change to tmp2.
git co master
[ "$(git current-branch)" == "master" ]
[ "$(cd "$tmp2" && git current-branch)" == "test" ]
git copy-diffs tmp2
check_cmd git current-branch

# Initialize an untracked file `foo`; verify that tmp1 has it and tmp2 doesn't.
echo a > foo
[ "$(git lso)" == "foo" ]
[ "$(cd "$tmp2" && git lso)" == "" ]

git copy-diffs tmp2
check_cmd git status -s
check_cmd check_hashes
check_cmd git lso
check_cmd git for-each-ref


git add foo
git copy-diffs tmp2
check_cmd git status -s
check_cmd git for-each-ref
check_cmd check_hashes

echo b >> foo
git copy-diffs tmp2
check_cmd git status -s
check_cmd check_hashes
check_cmd git for-each-ref
check_cmd git diff
check_cmd git diff --cached

git commit -m "foo"
git copy-diffs tmp2
check_cmd git status -s
check_cmd check_hashes
check_cmd git for-each-ref
check_cmd git diff
check_cmd git diff --cached

# Verify that creating a branch triggers a copy of it
git reset --hard HEAD
git co master
git branch -D test
git copy-diffs tmp2
check_cmd git local-branches
