#!/usr/bin/env bash

set -ex

base=HEAD
msg=
ARGS=()

while [ $# -gt 0 ]
do
    unset OPTIND
    unset OPTARG
    while getopts ":b:m:" opt
    do
      case "$opt" in
        b) base="$OPTARG";;
        m) msg="$OPTARG";;
        *) ;;
      esac
    done
    shift $((OPTIND-1))
    ARGS+=("$1")
    shift
done

if [ -z "$msg" ]; then
  msg="Octo-merge:"
  for arg in "${ARGS[@]}"; do
    msg="$msg $arg"
  done
fi

tree="$(git log -n 1 --format='%T' "$base")"

parent_args=()
add_parents() {
  for arg in "$@"; do
    parent_args+=( "-p" "$arg" )
  done
}

if [ ${#ARGS[@]} -eq 1 ]; then
  add_parents HEAD
fi
add_parents "${ARGS[@]}"

commit="$(git commit-tree "$tree" "${parent_args[@]}" -m "$msg")"

git reset --hard "$commit"
