#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <commit>" >&2
    exit 1
fi

cd="$(git log -1 --format=%cd "$1")"
echo "Setting committer date to $cd" >&2
GIT_COMMITTER_DATE="$cd" git commit --amend --no-edit
