#!/bin/bash

# Commit staged changes, with a message.

if [ $# -eq 0 ]; then
	echo "Usage: git cam [-a] <commit message> [auditor1,auditor2,...]"
	exit 1
fi

if [ "$1" = "-a" ]; then
	shift
	all="-a "
else
	all=""
fi

if [ $# -gt 1 ]; then
	auditors="$2"
else
	auditors=
fi

msg="$1"
if [ ! -e "$auditors" ]; then
	msg="$msg

Auditors: $auditors"
fi

git commit ${all}-m "$msg"
