#!/bin/sh

# Amend the previous commit with all staged changes.

git diff --cached --exit-code
if [ $? -gt 0 ]; then
	echo "**** Committing changes ****"
	git commit --amend --no-edit
else
	echo "**** No changes found ****"
fi

