#!/usr/bin/env bash

if [ $# -gt 1 ]; then
    echo "Usage: $0 [commit]" >&2
    exit 1
else
    cd="$(git log -1 --format=%cd)"
    if [ $# -eq 1 ]; then
        ad="$(git log -1 --format=%ad "$1")"
    else
        ad="$cd"
    fi
fi

echo "Setting author date to $ad" >&2
GIT_COMMITTER_DATE="$cd" git commit --amend --date "$ad" --no-edit
