#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <commit>" >&2
    exit 1
fi

ad="$(git log -1 --format=%ad "$1")"
cd="$(git log -1 --format=%cd)"
echo "Setting author date to $ad" >&2
GIT_COMMITTER_DATE="$cd" git commit --amend --date "$ad" --no-edit
