#!/usr/bin/env bash

# Run git commit and git push
#
# The remote to push to is the first argument (if it matches a git remote), or $DEFAULT_REMOTE.

if [ $# -gt 0 ] && git remote-exists "${@: -1}"; then
  IFS=, read -ra remotes <<< "${@: -1}"
  set -- "${@:1:(($#-1))}"
else
  read -ra remotes < <(git remote)
fi
echo "Pushing to: ${remotes[@]}"


git commit "$@" && for remote in "${remotes[@]}"; do git push "$remote"; done
