#!/usr/bin/env bash

if ! git diff --exit-code --cached; then
  echo "Expected no staged changes" >&2
  exit 1
fi

readarray -t files <<<"$(git --no-pager diff --name-only)"
for file in ${files[@]}; do
  git commit-basename "$file"
done
