#!/bin/sh

# Amend the last commit with all local staged and unstaged changes.

git diff --exit-code
if [ $? -gt 0 ]; then
	echo "**** Committing changes ****"
	git commit -a --amend --no-edit
else
	echo "**** No changes found ****"
fi

