#!/usr/bin/env bash

set -ex

head_tree="$(git log -n 1 --format='%T' HEAD)"

parents_str=
parent_args=()
add_parents() {
  for arg in "$@"; do
    parent_args+=( "-p" "$arg" )
    parents_str="${arg}${parents_str:+, }${parents_str}"
  done
}

add_parents "$@"

if [ $# -eq 1 ]; then
  add_parents HEAD
fi

new_tree="$(git commit-tree "$head_tree" "${parent_args[@]}" -m "Merge in $parents_str")"

git reset --hard "$new_tree"
