#!/usr/bin/env bash

# Show a pretty `git log` with a graph.
#
# Usage:
#
# $ git graph [-a|-ac] [-d] [-l] ...
#
# -a: print "author" datetimes (default: "committer")
# -ac: print "author" and "committer" datetimes
# -A: order commits by author date (default: committer date)
# -C: show committer name and email (default: author)
# -d: render ISO datetimes (default: "relative")
# -e: show author/committer email (default: name)
# -H: omit SHA hashes from output
# -l: render "local" datetimes (default: "relative")
# -u: include upstream ("tracked") branch
#
# Other args are passed through to `git log`

set -e

args=()
author_fmt="%an"
date_order=--date-order
show_committer=
show_email=
email_color=cyan
date_fmt='%cd'
date_style="relative"
include_upstream=
omit_sha=
while [ $# -gt 0 ]; do
    arg="$1"; shift
    case "$arg" in
    -a) date_fmt="%ad" ;;
    -ac) date_fmt="%ad %C(green)%cd" ;;
    -A) date_order=--author-date-order ;;
    -C) show_committer=1 ;;
    -d) date_style="iso" ;;
    -e) show_email=1 ;;
    -H) omit_sha=1 ;;
    -l) date_style="local" ;;
    -u) include_upstream=1 ;;
    *) args+=("$arg") ;;
    esac
done

if [ -n "$show_committer" ]; then
    if [ -n "$show_email" ]; then
        author_fmt="%cn %C($email_color)<%ce>"
    else
        author_fmt="%cn"
    fi
else
    if [ -n "$show_email" ]; then
        author_fmt="%an %C($email_color)<%ae>"
    else
        author_fmt="%an"
    fi
fi

if [ -n "$include_upstream" ]; then
    args+=("$(git tracked-branch)")
fi

set -- "${args[@]}"

style=--graph
for arg in "$@"; do
  if [ "$arg" = "--no-walk" ]; then
    style=--no-walk
    break
  fi
done

# Build format string based on whether SHAs should be omitted
if [ -n "$omit_sha" ]; then
  format_string="%C(blue)${date_fmt} %C(red)${author_fmt}%C(reset)%C(auto)%d %s"
else
  format_string="%C(auto)%h %C(blue)${date_fmt} %C(red)${author_fmt}%C(reset)%C(auto)%d %s"
fi

git log \
  "$style" \
  "--format=$format_string" \
  "--date=$date_style" \
  "$date_order" \
  "$@"
