#!/bin/bash

# Determine whether a git command exists.

usage() {
  err "Usage: $0 <cmd>"
  exit 1
}

if [ $# -ne 1 ]; then
  usage
fi

if [[ "$1" =~ git-* ]]; then
  cmd="${1#git-*}"
  full_cmd="$1"
else
  cmd="$1"
  full_cmd="git-$cmd"
fi

if which "$full_cmd" &> /dev/null; then
  exit 0
fi

if git help "$cmd" &> /dev/null; then
  exit 0
fi

git config alias."$cmd"

