#!/usr/bin/env bash

# Find octopus merge-base for inputs.

from=
if [ $# -lt 1 ]; then
  from=origin/HEAD
else
  from="$1"
  shift
fi

to=
if [ $# -lt 1 ]; then
  to=HEAD
else
  to="$1"
  shift
fi

git merge-base --octopus "$from" "$to" "$@"
