#!/usr/bin/env bash

# Find octopus merge-base for inputs.

from=
if [ $# -lt 1 ]; then
  from="$(git tracked-branch)"
  if [ -z "$from" ]; then
    if [ -z "$DEFAULT_REMOTE" ]; then
      echo "No tracked-branch found, and \$DEFAULT_REMOTE not set" >&2
      exit 1
    fi
    from="$DEFAULT_REMOTE/HEAD"
  fi
else
  from="$1"
  shift
fi

to=
if [ $# -lt 1 ]; then
  to=HEAD
else
  to="$1"
  shift
fi

git merge-base --octopus "$from" "$to" "$@"
