#!/bin/bash

mirror_remote="$1"
shift

dt() {
   date +%Y-%m-%d-%H:%M:%S
}

log() {
   echo "*** $(dt) $PWD: $@"
}

log "remote $mirror_remote, watchman found changed paths: $@"

filter_files() {
   for file in "$@"; do
      if [ ! -d "$file" ] && ! git check-ignore "$file" &> /dev/null && [ "$file" != ".git/index.lock" ]; then
         echo "$file"
      fi
   done
}
git_files=$(filter_files "$@")

if [ -z "$GIT_HELPERS_HOME" ]; then
   source .git-rc
fi

set -e

copy_files() {
   git command-exists copy-diffs
   if ! git copy-diffs "$mirror_remote"; then
     log "** Failed!"
   fi
   log "Done"
}

if [ -n "$git_files" ]; then
   log "Found changed files: $git_files"
   copy_files
else
   log "Skipping"
fi
