#!/bin/bash

set -e

source "$GIT_HELPERS_HOME"/config/.helpers-rc
if ! which watchman &> /dev/null; then
  err "Can't find watchman"
fi

root="$(git root)"
cur_repo_name="$(basename "$root")"
watchman_dir="$GIT_HELPERS_HOME"/watchman
logs_dir="$TMPDIR/logs"
mkdir -p "$logs_dir"

mirror_remote="$(git mirror-remote "$@")"
stdout_file="$logs_dir/$cur_repo_name-copy-diffs.stdout"
stderr_file="$logs_dir/$cur_repo_name-copy-diffs.stderr"

watchman -j <<EOF
[
  "trigger",
  "$root",
  {
    "name": "copy-diffs",
    "command": [ "$watchman_dir/copy-diffs-script", "$mirror_remote" ],
    "append_files": true,
    "stdout": ">>$stdout_file",
    "stderr": ">>$stderr_file"
  }
]
EOF

echo "Watching $root, copying changes to remote $mirror_remote, logging to $logs_dir/$cur_repo_name-copy-diffs.std{out,err}"
