#!/usr/bin/env bash

# Run a git command in a different git directory
#
# Usage:
#
# git <other repo root dir> <args...>

if [ $# -eq 0 ]; then
  echo "Usage: $0 <git dir> [args...]" >&2
  exit 1
fi

dirs="$1"
shift
IFS=, read -ra dirs <<< "$dirs"
for dir in "${dirs[@]}"; do
  if [ ${#dirs[@]} -gt 1 ]; then
    echo "** $dir:"
    echo ""
  fi
  git --git-dir="$dir"/.git --work-tree="$dir" "$@"
done
