#!/usr/bin/env bash

set -eo pipefail

usage() {
  echo "Usage: $0 <attr type> [value]" >&2
  exit 1
}

global=()
cmd=command
while getopts "gt" opt; do
  case "$opt" in
    g) global=(--global) ;;
    t) cmd=textconv ;;
    \?) usage \\
  esac
done
shift $((OPTIND-1))

if [ $# -eq 0 ]; then
  usage
else
  type="$1"; shift
fi

key="diff.$type.$cmd"
git config "${global[@]}" "$key" "$@"
