#!/usr/bin/env bash

if [ -z "$GLOBAL_GIT_IGNORE_PATH" ]; then
  echo "No \$GLOBAL_GIT_IGNORE_PATH set" >&2
  exit 1
fi

if [ $# -eq 0 ]; then
  comm -13 <(sort "$GLOBAL_GIT_IGNORE_PATH") <(cat | sort) >> "$GLOBAL_GIT_IGNORE_PATH"
else
  cat "$@" | "$0"
fi
