#!/usr/bin/env bash

set -eo pipefail

err() {
  echo "$@" >&2
}

usage() {
  err "Usage: $0 [-g] [-t] [-u] <attr type> [value]"
  err
  err "  -g: --global"
  err "  -t: manipulate diff.<attr>.textconv instead of diff.<attr>.command"
  err "  -u: unset diff/textconv command"
  exit 1
}

global=()
cmd=command
unset=()
while getopts "gtu" opt; do
  case "$opt" in
    g) global=(--global) ;;
    t) cmd=textconv ;;
    u) unset=(--unset) ;;
    \?) usage ;;
  esac
done
shift $((OPTIND-1))

if [ $# -eq 0 ]; then
  usage
else
  type="$1"; shift
fi

key="diff.$type.$cmd"

if [ ${#unset[@]} -gt 0 ]; then
  if [ $# -gt 0 ]; then
    usage
  fi
  cur="$(git config "${global[@]}" "$key")"
  if [ -n "$cur" ]; then
    err "Unsetting $key: $cur"
  fi
fi

cmd=(git config "${global[@]}" "${unset[@]}" "$key" "$@")
echo "${cmd[*]}" >&2
"${cmd[@]}"
