#!/usr/bin/env bash

set -eo pipefail

if [ "$1" == -g ] || [ "$1" == --global ]; then
  global=(--global); shift
else
  global=()
fi

excludesfile="$(git config "${global[@]}" core.excludesfile)"
if [ -z "$excludesfile" ]; then
  echo 'No `core.excludesfile` found; set via: `git config '"${global[*]}"' core.excludesfile <path>`' >&2
  exit 1
fi

mapfile -t new_ignores < <(comm -13 <(sort "$excludesfile") <(for arg in "$@"; do echo "$arg"; done | sort))

for new_ignore in "${new_ignores[@]}"; do
  echo "$excludesfile: appending $new_ignore" >&2
  echo "$new_ignore" >> "$excludesfile"
done
