#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  echo "Usage: $0 <ssh private key path>" >&2
  exit 1
fi
file="$1"; shift

if [ ! -e "$file" ]; then
  echo "SSH key not found: $file" >&2
  exit 2
fi

file="$(readlink -f "$file")"

echo "Setting Git SSH key: $file"
git config core.sshCommand "ssh -i $file"
