#!/usr/bin/env bash

set -eo pipefail

mapfile -t files < <(git config --global --get-all core.excludesfile)
n="${#files[@]}"
if [ "$n" -ne 1 ]; then
  echo "Attempting to ignore \"$*\", found $n core.excludesfiles: ${files[*]}" >&2
  exit 1
fi

excludesfile="${files[0]}"
if [ $# -eq 0 ]; then
  comm -13 <(sort "$excludesfile") <(cat | sort) >> "$excludesfile"
else
  cat "$@" | "$0"
fi
