#!/usr/bin/env bash

config="$1"
shift
for file in "$@"; do
   if [ -f "$file" ] && ! git config --global --get-all "$config" | grep -q "^$file\$"; then
       cmd=(git config --global --add "$config" "$file")
       echo "${cmd[*]}" >&2
       "${cmd[@]}"
   fi
done
