#!/usr/bin/env bash

set -e

global=()
global_msg=
author_only=
committer_only=
while getopts "acg" opt; do
  case "$opt" in
    a) author_only=1 ;;
    c) committer_only=1 ;;
    g) global=("--global"); global_msg="global " ;;
    \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
  esac
done
shift $((OPTIND -1))

name="$(git config "${global[@]}" user.name || true)"
email="$(git config "${global[@]}" user.email)"

if [ -z "$committer_only" ]; then
  if [ -n "$GIT_AUTHOR_NAME" ]; then
    author_name="$GIT_AUTHOR_NAME"
  elif [ -z "$name" ]; then
    echo 'No $GIT_AUTHOR_NAME or `config '"${global_msg}"'user.name` found' >&2
    exit 1
  else
    author_name="$name"
  fi
  if [ -n "$GIT_AUTHOR_EMAIL" ]; then
    author_email="$GIT_AUTHOR_EMAIL"
  elif [ -z "$email" ]; then
    echo 'No $GIT_AUTHOR_EMAIL or `config '"${global_msg}"'user.email` found' >&2
    exit 1
  else
    author_email="$email"
  fi
  author="$author_name <$author_email>"
fi
if [ -z "$author_only" ]; then
  if [ -n "$GIT_COMMITTER_NAME" ]; then
    committer_name="$GIT_COMMITTER_NAME"
  elif [ -z "$name" ]; then
    echo 'No $GIT_COMMITTER_NAME or `config '"${global_msg}"'user.name` found' >&2
    exit 1
  else
    committer_name="$name"
  fi
  if [ -n "$GIT_COMMITTER_EMAIL" ]; then
    committer_email="$GIT_COMMITTER_EMAIL"
  elif [ -z "$email" ]; then
    echo 'No $GIT_COMMITTER_EMAIL or `config '"${global_msg}"'user.email` found' >&2
    exit 1
  else
    committer_email="$email"
  fi
  committer="$committer_name <$committer_email>"
fi

if [ -n "$author_only" ]; then
  echo "$author"
elif [ -n "$committer_only" ]; then
  echo "$committer"
elif [ "$author" == "$committer" ]; then
  echo "$author"
else
  echo "$author"
  echo "$committer"
fi
