#!/usr/bin/env bash

if $# -ne 2; then
  echo "Usage: $0 <name> <email>" >&2
  exit 1
fi

name="$1"; shift
email="$1"; shift

git config --global user.name "$name"
git config --global user.email "$email"
