#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    author="$(git author)"
    echo "Setting author: $author" >&2
elif [ $# -eq 1 ]; then
    author="$1"; shift
elif [ $# -eq 2 ]; then
    name="$1"; shift
    email="$1"; shift
    author="$name <$email>"
    echo "Setting author: $author" >&2
else
    echo "Usage: git set-author [name <email>]" >&2
    echo "Usage: git set-author <name> <email>" >&2
    exit 1
fi

cmd=(git commit --amend  --no-edit --allow-empty --author "$author")
echo "Running: ${cmd[*]}" >&2
"${cmd[@]}"
