#!/bin/bash

# Print all broken symlinks in the repo.

found=0
for f in $(g links "$@"); do
  pushd "$(dirname "$f")" > /dev/null
  dest="$(readlink "$(basename "$f")")"
  if [ ! -s "$dest" ]; then
    echo "$f: $dest"
    found=1
  fi
  popd > /dev/null
done

exit $found
