#!/bin/bash

link_only=
if [ "$1" == "-s" ]; then
  link_only=1
  shift
fi

if [ $# -ne 2 ]; then
  err "Usage: $0 <full git extension> <git alias>"
  exit 1
fi

dir="$(dirname "${BASH_SOURCE[0]}")"

cd "$dir"
full="git-$1"
short="git-$2"

verify_commands_dont_exist() {
  for arg in "$@"; do
    if git command-exists "$arg"; then
      err "Found existing git command: $arg"
      exit 1
    fi
  done
}

if [ ! $link_only ]; then
  verify_commands_dont_exist "$full" "$short"
fi

if [ ! -e "$full" ]; then
  err "Can't find $PWD/$full"
  exit 1
fi

chmod 755 "$full"

cd "aliases"
ln -s ../"$full" "$short"
git add "$short"

