#!/usr/bin/env bash

# This script takes care of some common steps involved in adding new scripts to this repo:
#
#   - mark the script as executable
#   - create an alias to it

if [ $# -ne 2 ]; then
  err "Usage: $0 <full git extension> <git alias>"
  exit 1
fi

cd "$GIT_HELPERS_HOME"
set -e
source config/.helpers-rc

base="git-$1"
alias="git-$2"

verify_commands_dont_exist() {
  for arg in "$@"; do
    if git command-exists "$arg"; then
      err "Found existing git command: $arg"
    fi
  done
}

verify_commands_dont_exist "$alias"

full=$(find . -name "$base" | sed "s_^\./__" | sort)
num_hits="$(count $full)"
if [ "$num_hits" -eq 0 ]; then
  err "Can't find git script named $base below $PWD"
elif [ "$num_hits" -gt 1 ]; then
  echo "Found $num_hits candidates; choose one:"
  select f in $full; do
    full="$f"
    break
  done
fi

chmod 755 "$full"
cd "$(dirname "$(abspath "$full")")"

mkdir -p aliases
cd aliases
if [ -e "$alias" -o -L "$alias" ] && ! prompt "$PWD/$alias already exists; overwrite? [Y/n]: " ; then
  exit 1
fi
ln -sf ../"$base" "$alias"
git add "$alias"

