#!/usr/bin/env bash

cd "$(git root)"

set -ex

test() {

  expected="${@: -1}"
  args=("${@:1:(${#@}-1)}")

  actual="$(git relpath ${args[@]})"

  if [ "$actual" != "$expected" ]; then
    echo "Failed: \`git relpath $args\`: expected $expected, actual $actual" 1>&2
    exit 1
  fi

}

test log/aliases log/aliases
test log/aliases/ log/aliases
test test/admin/ test/admin
test test/nav/ test/nav
test test/nav/relpath-test test/nav/relpath-test

test diff/ test/nav/relpath-test ../test/nav/relpath-test
test diff test/nav/relpath-test ../test/nav/relpath-test

test test/admin test/nav/relpath-test ../nav/relpath-test
test test/admin test/nav/relpath-test ../nav/relpath-test
