#!/bin/bash

# Clean out old git branches: iterate through local branches in order of least
# recently modified, display information about the branch, and prompt for
# deletion of the branch.

set -e
source "$GIT_HELPERS_HOME"/config/.helpers-rc

branches=$(git local-branches)
num_branches=$(count $branches)
idx=

export clear="\033[0m"           # Text Reset
export Red="\033[0;31m"          # Red
export Green="\033[0;32m"        # Green

if [ "$1" == "-n" ]; then
    echo -e "${Green}Dry run..${clear}"
    dry_run=1
    prompt="${Red}Delete${clear} ${Green}(but not really)${clear}"
else
    dry_run=0
    prompt="${Red}Delete${clear}"
fi

OLD_IFS="$IFS"
IFS=$'\n'
for b in $(git local-branches -t); do
    let idx=$idx+1

    lastdate=$(git log -n 1 "$b" --format="%ad" --)
    relativedate=$(git log -n 1 "$b" --format="%ar" --)

    echo "Branch $idx of $num_branches: $b"
    echo "Last modified $relativedate: $lastdate"
    echo -e "\t\c"; git branch --list -vv "$b"

    if prompt "$prompt $b? [Y/n]: "; then
        if [ ! "$dry_run" ]; then
            git branch -D "$b"
        fi
        echo "${Red}Deleted${clear}"
    fi
    echo ''
done
IFS="$OLD_IFS"
