#!/usr/bin/env bash

# Output local branches; -t flag sorts in reverse-chron order.

if [ $# -gt 0 -a "$1" == "-t" ]; then
  git for-each-ref --format='%ct %(refname:short)' refs/heads | sort -nrk 1 | awk '{ print $2 }'
else
  git for-each-ref --format='%(refname:short)' refs/heads
fi

