#!/usr/bin/env bash

# Set the upstream ref for the current branch. Usage:
#
#   $ git branch-upstream [upstream ref] <branch>

if [ $# -eq 0 ]; then
  upstream="$(git default-remote)/main"
else
  upstream="$1"
  shift
fi

git branch --set-upstream-to "$upstream" "$@"
