#!/usr/bin/env bash
#
# Reset a branch to a given ref, and optionally `checkout` it.
#
# Usage:
#
# $ git branch-reset [-c|--checkout] [branch=main [ref=HEAD]]

set -e

checkout=
if [ "$1" == "-c" ] || [ "$1" == "--checkout" ]; then
    checkout=1
    shift
fi

if [ $# -gt 0 ]; then
  branch="$1"
  shift
else
  branch=main
fi

if [ $# -gt 0 ]; then
  ref="$1"
  shift
else
  ref=HEAD
fi

# Check if we're trying to reset the current branch
current_branch="$(git branch --show-current)"
if [ "$branch" = "$current_branch" ]; then
  # Can't use 'git branch -f' on current branch, use reset instead
  git reset --hard "$ref"
else
  git branch -f "$branch" "$ref"

  if [ -n "$checkout" ]; then
    git checkout "$branch"
  fi
fi
