#!/usr/bin/env bash

# Pretty-print remote branch info.

git branch -rvv --list "$@" | \
awk -F' ' '{print $1}' | \
xargs git --no-pager show -s --format="%d %h %ci (%cr) %s" | \
sed -n "s/\(.\)/\1/p" | \
python "$(dirname "${BASH_SOURCE[0]}")"/../git_helpers/util/remote_branch_infos.py

