#!/usr/bin/env bash

# Checkout a new branch and set its upstream (default to origin/master).

set -e
source "$GIT_HELPERS_HOME"/config/.helpers-rc

if [ $# -eq 0 ]; then
	echo "Usage: git new-branch <new branch name> [<tracking branch name=origin/master>]"
	exit 1
fi

new_branch_name="$1"
if [ $# -gt 1 ]; then
	tracking_branch_name="$2"
else
	if git rev-parse --verify -q origin/HEAD; then
		tracking_branch_name="origin/HEAD"
	elif git rev-parse --verify -q origin/master; then
		tracking_branch_name="origin/master"
	else
		err "Neither origin/HEAD nor origin/master found"
	fi
fi

git checkout -b "$new_branch_name" -t "$tracking_branch_name"

