#!/usr/bin/env python

"""Pretty-print all local branches."""

import os
import sys

if __name__ == '__main__':
    file_path = os.path.realpath(__file__)
    branches_dir = os.path.dirname(file_path)
    root_dir = os.path.dirname(branches_dir)
    sys.path.append(root_dir)

from util.branch_infos import BranchInfos

BranchInfos()
