#!/usr/bin/env bash

# Checkout a new branch and set its upstream (default to $DEFAULT_REMOTE/master).

set -e
source "$GIT_HELPERS_HOME"/config/.helpers-rc

remote="$(git default-remote)"

if [ $# -eq 0 ]; then
  echo "Usage: git new-branch <new branch name> [<tracking branch name=$remote/master>]"
  exit 1
fi

new_branch_name="$1"
if [ $# -gt 1 ]; then
  tracking_branch_name="$2"
else
  if git rev-parse --verify -q "$remote"/HEAD; then
    tracking_branch_name="$remote"/HEAD
  elif git rev-parse --verify -q "$remote"/master; then
    tracking_branch_name="$remote/master"
  else
    err "Neither $remote/HEAD nor $remote/master found"
  fi
fi

git checkout -b "$new_branch_name" -t "$tracking_branch_name"

