#!/usr/bin/env python

import os
import sys

if __name__ == '__main__':
    file_path = os.path.realpath(__file__)
    branches_dir = os.path.dirname(file_path)
    root_dir = os.path.dirname(branches_dir)
    ssys.path.insert(0, root_dir)

from util.remotes import get_mirror_remote

print(get_mirror_remote().name)
