#!/usr/bin/env bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 <src> <dst>" >&2
fi

src="$1"; shift
dst="$1"; shift

git remote add "$dst" "$(git remote get-url "$src")"
git fetch --recurse-submodules "$dst"
