#!/usr/bin/env bash

# Check whether a remote exists. If a second argument is present, verify that
# it matches the remote's path.

set -e

IFS=, read -ra remotes <<< "$1"
shift
if [ ${#remotes[@]} -gt 1 ]; then
  for remote in "${remotes[@]}"; do
    git remote-exists "$remote"
  done
else
  remote="${remotes[1]}"
  git remote show -n "$remote" &> /dev/null
  if [ $# -gt 0 ]; then
    diff -q <(echo "$1") <(git ls-remote --get-url "$remote") > /dev/null
  fi
fi
