#!/usr/bin/env bash

set -eo pipefail

usage() {
  echo "$0 [-r remote] [ref=HEAD]" >&2
  exit 1
}

remote=
while getopts "r:" opt; do
  case $opt in
    r) remote="$OPTARG" ;;
    \?) usage ;;
  esac
done
shift $((OPTIND-1))

if [ $# -eq 0 ]; then
  ref=HEAD
elif [ $# -eq 1 ]; then
  ref="$1"; shift
else
  echo "Usage: $0 [ref=HEAD]" >&2
  exit 1
fi

if [ -z "$remote" ]; then
  remote="$(git default-remote "$ref")"
fi

git branch --format '%(refname:short)' -r --points-at "$ref" | \
perl -ne "print if s/^$remote\///" | \
grep -v "^pr/"
