#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  from=origin
else
  from="$1"
  shift
fi

if [ $# -eq 0 ]; then
  to="$(git default-remote -n)"
else
  to="$1"
  shift
fi

if [ -z "$from" ]; then
  err "Empty 'src'"
  exit 1
fi

if [ -z "$to" ]; then
  err "Empty 'dest'"
  exit 1
fi

git remote rename "$from" "$to"
