#!/usr/bin/env python

"""Adds a mirrored git remote suitable for pushing to using `git copy-diffs`"""

__author__ = "Ryan Williams"

import os
import sys

if __name__ == '__main__':
    file_path = os.path.realpath(__file__)
    branches_dir = os.path.dirname(file_path)
    root_dir = os.path.dirname(branches_dir)
    sys.path.append(root_dir)

import subprocess
from util.remotes import get_remotes, maybe_remove_remote_if_exists

if len(sys.argv) < 3:
    remote_name = os.getenv('DEFAULT_MIRROR_REMOTE_NAME')
    remote_host = os.getenv('DEFAULT_MIRROR_REMOTE_HOST')
    remote_dir = os.getenv('DEFAULT_MIRROR_REMOTE_DIR')
    if not remote_name or not remote_host or not remote_dir:
        print 'Usage: git add-mirror-remote <remote_name> <remote_url>'
        sys.exit(1)
    root = subprocess.check_output(['git', 'root']).strip()
    basename = os.path.basename(root)
    remote_url = '%s:%s/%s' % (remote_host, remote_dir, basename)
    print 'Using default remote url: %s' % remote_url
else:
    remote_name = sys.argv[1]
    remote_url = sys.argv[2]


if not maybe_remove_remote_if_exists(remote_name):
    sys.exit(1)


subprocess.check_output(
    ['git', 'remote', 'add', '--mirror=push', remote_name, remote_url]
)

remotes = get_remotes()

if remote_name not in remotes:
    raise Exception('Failed to add remote %s' % remote_name)

remote = remotes[remote_name]

repo_init_commands = [
    ['git', 'init'],
    ['git', 'config', 'receive.denyCurrentBranch', 'false'],
    ['git', 'config', 'receive.denyNonFastForwards', 'false'],
    ['git', 'config', 'receive.denyDeleteCurrent', 'false'],
]

if remote.is_remote:
    remote_cmd = ' && '.join(
        ([ 'mkdir %s' % remote.path ] if remote.path else  []) +
        [ 'cd %s' % (remote.path or '~') ] +
        map(' '.join, repo_init_commands)
    )

    print 'Running remote cmd: %s' % remote_cmd

    subprocess.check_output(['ssh', remote.host, remote_cmd])

    print 'Done!'
else:
    print 'Initializing local repo'
    subprocess.check_output(['mkdir', '-p', remote.path])
    os.chdir(remote.path)
    map(subprocess.check_output, repo_init_commands)
    print 'Done!'
