#!/usr/bin/env bash

if [ "$#" -gt 0 ]; then
  remote="$1"
  shift
else
  remote="${DEFAULT_GIT_REMOTE}"
fi

if [ "$#" -gt 0 ]; then
  branch="$1"
  shift
else
  branch=master
fi

git remote set-head "$remote" "$branch"
