#!/usr/bin/env bash

# Check whether a remote exists. If a second argument is present, verify that
# it matches the remote's path.

set -e

remote="$1"
git remote show -n "$remote" &> /dev/null
shift
if [ $# -gt 0 ]; then
  diff -q <(echo "$1") <(git ls-remote --get-url "$remote") > /dev/null
fi
