#!/usr/bin/env bash

plan_file=
dry_run=
# Process only our script options, stop at first non-option or unknown option
while [ $# -gt 0 ]; do
  case "$1" in
    -f)
      plan_file="$2"
      shift 2
      ;;
    -n)
      dry_run=-n
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      # Unknown option, assume it's for git-rebase
      break
      ;;
    *)
      # Non-option argument, pass to git-rebase
      break
      ;;
  esac
done

cmd=(git rebase -i "$@")

if [ -n "$plan_file" ]; then
  plan="$(cat "$plan_file")"
else
  plan="$(cat)"
fi
echo "Rebase plan:" >&2
echo "$plan" >&2

if [ -n "$dry_run" ]; then
  exit
fi

export GIT_SEQUENCE_EDITOR="echo '$plan' >"
"${cmd[@]}"
