#!/usr/bin/env bash

if [ "$1" == "-n" ]; then
    dry_run=-n
    shift
else
    dry_run=
fi

cmd=(git rebase -i "$@")

if [ -n "$dry_run" ]; then
    echo "Would run ${cmd[@]}:" >&2
    cat
    exit
else
    echo "Running ${cmd[@]}" >&2
fi

stdin="$(cat)"
trimmed_input="$(echo "$stdin" | awk '{ print $1,$2 }')"
echo "Rebase plan:" >&2
echo "$trimmed_input" >&2

GIT_SEQUENCE_EDITOR="echo '$trimmed_input' >" "${cmd[@]}"
