#!/usr/bin/env bash

if [ "$1" == "-n" ]; then
    dry_run=-n
    shift
else
    dry_run=
fi

cmd=(git rebase -i "$@")

if [ -n "$dry_run" ]; then
    echo "Would run ${cmd[*]}:" >&2
    cat
    exit
else
    echo "Running ${cmd[*]}" >&2
fi

stdin="$(cat)"
echo "Rebase plan:" >&2
echo "$stdin" >&2

GIT_SEQUENCE_EDITOR="echo '$stdin' >" "${cmd[@]}"
