#!/usr/bin/env bash

# Print the SHA that is being rebased.
if [ -f .git/rebase-apply/orig-head ]; then
	cat .git/rebase-apply/orig-head
elif [ -f .git/rebase-merge/orig-head ]; then
	cat .git/rebase-merge/orig-head
else
	echo "Error: couldn't find .git/rebase-{merge,apply}/orig-head" >&2
	exit 1
fi
