#!/usr/bin/env bash
#
# During a rebase, execute a command, and commit its contents (or amend the previous commit, with `-a`/`--amend`).
#
# e.g.:
# ```bash
# Rebase last 5 commits, run `ruff` linter, amend changes to each.
# grx 'g rxsa ruff format .' HEAD~5
# ```

set -e

if ! [ -d .git/rebase-merge ] && ! [ -d .git/rebase-apply ]; then
  echo "$0 can only be run during a rebase" >&2
  exit 1
fi

if ! git diff --exit-code; then
  echo "$0 requires a clean worktree" >&2
  exit 1
fi

amend=
if [ "$1" = -a ] || [ "$1" = --amend ]; then
  amend=1
  shift
fi

echo "$(basename "$0") executing: $*" >&2
"$@"

if ! git diff --exit-code; then
  sha="$(git log -1 --format=%h)"
  echo -n "$sha: found updated files; " >&2
  if [ -n "$amend" ]; then
    echo "amending" >&2
    git commit -a $amend --no-edit
  else
    echo "committing" >&2
    git commit -a -m '`'"$*"'`'
  fi
else
  echo "$sha: no updated files found" >&2
fi
