#!/bin/bash -i

set -e

err() {
  echo "$0: $*" >&2
}

usage() {
  err "Usage: $0 [-c] [-v]"
  err '  -c  Print histogram of added completions, grouped by length'
  err '  -v  Print all added completions'
  err
  err 'Compare the files `{before,after}/compgen-c` (outputs of two runs of `compgen -c`, before and after installing "git-helpers").'
  err 'These files are written during the `git-helpers.dockerfile` build, before this script is invoked.'
  exit 1
}

verbose=
counts=
while getopts "cv" opt; do
  case "$opt" in
    c) counts=1 ;;
    v) verbose=1 ;;
    \?) usage ;;
  esac
done

excludes=(
  # Vars/functions provided by `.gitcomplete`
  '^_'
  # Helper scripts, not Git related
  append_subdir_to_path
  append_to_path
  define_function
  defn
)
exclude_args=()
for exclude in "${excludes[@]}"; do
  exclude_args+=(-e "$exclude")
done

cmd=(grep -v "${exclude_args[@]}")

_comm() {
  comm "$@" <("${cmd[@]}" before/compgen-c) <("${cmd[@]}" after/compgen-c)
}

comm_count() {
  _comm "$@" | wc -l
}

rms="$(comm_count -23)"      # Present before, not after
adds="$(comm_count -13)"     # Present after, not before
boths="$(comm_count -12)"    # Present before and after
(( afters = adds + boths ))  # Total completions available, "after"

if [ -n "$verbose" ]; then
  echo "$adds new completions:"

  _comm -13 \
  | p 'echo -n "{} "; echo {} | wc -c' \
  | sort -nk2 \
  | cut -d' ' -f1 \
  | grep -v '^git-' \
  | while read -r cmd; do
    n="${#cmd}"
    echo -n "$cmd"
    if [ $n -lt 10 ]; then
      (( s=10-$n ))
      printf "% ${s}s" ""
    fi
    gea="$(gea "$cmd" || true)"
    if [ -n "$gea" ]; then
      echo " = $gea"
    else
      echo
    fi
  done

  echo "$boths completions present before and after installing git-helpers"
  echo "$adds completions added by installing git-helpers ($rms removed, $afters total)"
else
  echo "$adds completions added by installing git-helpers"
fi
if [ -n "$counts" ]; then
  completions="$(_comm -13)"
  num2="$(echo "$completions" | grep '^g.$' | wc -l)"
  num3="$(echo "$completions" | grep '^g..$' | wc -l)"
  num4="$(echo "$completions" | grep '^g...$' | wc -l)"
  num5="$(echo "$completions" | grep '^g....$' | wc -l)"
  echo "By length:"
  echo "- 2 chars: $num2"
  echo "- 3 chars: $num3"
  echo "- 4 chars: $num4"
  echo "- 5 chars: $num5"
fi
