#!/usr/bin/env bash

set -e

if [ $# -eq 0 ]; then
  msg="$(git msg)"
  if [[ $msg =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    git tag -f "$msg"
  else
    echo "Usage: $0 [tag]" >&2
    echo "If no [tag] is provided, the current commit message is used as the tag, and expected to be of the form /^v?[0-9]+\.[0-9]+\.[0-9]+$/" >&2
    exit 1
  fi
else
  git tag -f "$@"
fi
