#!/usr/bin/env python

"""Pretty-print tags."""

import os
import sys

if __name__ == '__main__':
    file_path = os.path.realpath(__file__)
    branches_dir = os.path.dirname(file_path)
    root_dir = os.path.dirname(branches_dir)
    sys.path.insert(0, root_dir)

from util.tags import print_recent_tags

print_recent_tags()
