#!/usr/bin/env bash

remote="$1"
shift

if [ $# -eq 0 ]; then
  source=HEAD
  dest="$(git current-branch)"
else
  if [[ "$1" =~ : ]]; then
    source="${1%%:*}"
    dest="${1##*:}"
  else
    source=HEAD
    dest="$1"
  fi
  shift
fi

echo "$source -> $dest"

git push "$@" "$remote" "$source":"$dest"
