#!/usr/bin/env bash

# Push a branch (provided as a cmdline arg; default: current branch)
# to origin/master.

if [ $# -gt 0 ]; then
	arg="$1"
else
	arg="$(git cb)"
fi

git push origin "${arg}:master"

