#!/usr/bin/env bash
#
# Push current head to a provided remote branch

if [ $# -lt 2 ]; then
    echo "Usage: git push-head-to [...push flags] <remote> <dst branch>" >&2
    exit 1
fi

dst="${@: -1}"
set -- "${@:1:$(($#-1))}"
echo "$@"
#git push-x "$@" "HEAD:$dst"
