#!/usr/bin/env bash

if [ $# -gt 1 ]; then
  err "Usage: $0 [branch; default: current branch]"
fi

if [ $# -eq 0 ]; then
  branch="$(git current-branch)"
else
  branch="$1"
fi

git push origin "$branch"
