#!/usr/bin/env bash
#
# Push to one or more remotes (comma-separated), including tags

if [ "$1" == "-t" ]; then
    tags=1
else
    tags=
fi

if [ $# -gt 0 ]; then
  IFS=, read -ra remotes <<< "$1"
  shift
else
  remotes=()
  while read -r remote; do
    remotes+=("$remote")
  done < <(git remote)
fi

for remote in "${remotes[@]}"; do
  git push "$remote" "$@"
  if [ -n "$tags" ]; then
    git push --tags "$remote" "$@"
  fi
done
