#!/usr/bin/env bash
#
# Push to one or more remotes (comma-separated), including tags

if [ "$1" == "-t" ]; then
    tags=1
else
    tags=
fi

push() {
  git push "$@"
  if [ -n "$tags" ]; then
    git push --tags "$@"
  fi
}

if [ $# -gt 0 ]; then
  IFS=, read -ra remotes <<< "$1"
  shift
  for remote in "${remotes[@]}"; do
    push "$remote" "$@"
  done
else
  push "$@"
fi
