#!/bin/bash

# Output the current directory's relative path from the root of the current git repository.

source "$(git root)"/config/.helpers-rc

if [ $# -eq 0 ]; then
  "$0" "$PWD" "$(git root)"
  exit $?
elif [ $# -eq 1 ]; then
  "$0" "$PWD" "$1"
  exit $?
fi

from="${1%/}"
shift
if [ -d "$from" ]; then
  from_dir="$(abspath "$from")"
else
  from_dir="$(dirname "$(abspath "$from")")"
fi

for to in "$@"; do
  to_dir="$(abspath "$to")"
  tmp_to="${to_dir#/}"
  tmp_from="${from_dir#/}"

  while [ 1 ]; do

    from_segment="${tmp_from%%/*}"

    to_segment="${tmp_to%%/*}"

    if [ "$from_segment" != "$to_segment" -o -z "$from_segment" ]; then
      break
    fi

    if [ "$from_segment" == "$tmp_from" ]; then
      tmp_from=
    else
      tmp_from="${tmp_from#*/}"
    fi
    if [ "$to_segment" == "$tmp_to" ]; then
      tmp_to=
    else
      tmp_to="${tmp_to#*/}"
    fi

  done

  if [ -z "$tmp_from" ]; then
    echo "$tmp_to"
    continue
  fi

  dots_str=
  while [ 1 ]; do
    dots_str="../$dots_str"
    next_tmp_from="${tmp_from#*/}"
    if [ "$tmp_from" == "$next_tmp_from" ]; then
      break
    fi
    tmp_from="$next_tmp_from"
  done

  echo "${dots_str}${tmp_to}"
done
