#!/usr/bin/env bash

# Change to the top level of this git repository.
#
# Typically you'll want to `source` this for it to actually change the directory of the shell you
# are calling from.

cd "$(git root)"


