#!/usr/bin/env bash

set -e

usage() {
    echo "Usage: git submodule-auto-commit [-a]" >&2
    exit 1
}

include_unstaged=
if [ $1 == "-a" ]; then
    include_unstaged=1
    shift
fi

all=
if [ $# -eq 0 ]; then
    all=1
fi

if [ -z "$include_unstaged" ] && [ "$all" == "1" ]; then
    diff_args=(--cached)
else
    diff_args=()
fi

diffs="$(comm -12 <(git diff "${diff_args[@]}" --name-only "$@" | sort) <(git ls-tree HEAD "$@" | awk '$2=="commit" { print $4 }' | sort))"
echo "Changed submodules: $diffs" >&2

if [ "${#diffs[@]}" == "0" ]; then
    echo "No changed submodules found" >&2
    exit 1
fi

msg=
for sm in $diffs; do
    before="$(git ls-tree HEAD "$sm" | awk '{ print $3 }')"
    after="$(git x "$sm" full-hash)"
    subjects="$(git x "$sm" log --format=%s "$before..$after" | perl -pe 'chomp if eof; s/\n/, /')"
    msg="${msg:+$msg, }"
    msg="${msg}$sm: $subjects"
    git add "$sm"
done

git commit -m "$msg" "$@"
