#!/usr/bin/env bash

# Checkout "ours" version of conflicting files and continue a rebase.

set -e
git conflicting-checkout-ours
while read -r file; do
    git add "$file"
    echo "Added: $file"
done < <(git conflicting)
git rebase --continue
