#!/usr/bin/env bash
# Checkout "theirs" version of all conflicting files, and continue rebasing.

set -e
git conflicting-checkout-theirs
readarray -t conflicts < <(git conflicting)
git add-rebase-continue "${conflicts[@]}"
