#!/usr/bin/env bash
# Checkout "ours" version of all conflicting files, and continue rebasing.

set -e
git conflicting-checkout-ours
readarray -t conflicts < <(git conflicting)
git add-rebase-continue "${conflicts[@]}"
